name: Fedora Rawhide

on:
    push:
        paths-ignore:
            - 'gdal/doc/**'
    pull_request:
        paths-ignore:
            - 'gdal/doc/**'


jobs:

  fedora_rawhide:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
                ${{ github.workspace }}/ccache.tar.gz
          key: ${{ runner.os }}-cache-fedora-rawhide-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-cache-fedora-rawhide-

      - name: Build
        # Downgraded to fedora:34 instead of fedora:rawhide due to conflict between blas-devel-3.9.1-1.fc35.x86_64 and atlas-devel-3.10.3-13.fc34.x86_64
        # See https://github.com/OSGeo/gdal/runs/2324845532
        run: docker run --privileged=true -e CI -e WORK_DIR="$PWD" -v $PWD:$PWD -v /var/run/docker.sock:/var/run/docker.sock fedora:34 $PWD/.github/workflows/fedora_rawhide/start.sh
